version: 2
jobs:
  deployment-snapshot:
    steps:
      - checkout
      - run: gradlew artifactoryPublish -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$CI
workflows:
  version: 2
    create-snapshot:
      jobs:
        - build
        - test:
            requires:
              - build
        - deployment-snapshot:
            requires:
              - test