# Java Gradle CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test

  deploy-snapshot:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: gradle artifactoryPublish -Dsnapshot=true -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PbuildNumber=$CIRCLE_BUILD_NUM

  deploy-release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: gradle release -PbintrayUser=$BINTRAY_USER -Pbintray.key=$BINTRAY_KEY -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=$RELEASE_VERSION -Prelease.newVersion=$NEW_VERSION

workflows:
  version: 2
  build-snapshot-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy-snapshot:
          requires:
            - build